title: docker
description: learn the basic docker commands
details:
  intro:
    text: intro.rst
  steps:
  - name: step1
    title: Title for step 1
    text: step1.rst
  - name: step2
    title: Title for step 2
    text: step2.rst
  finish:
    text: finish.rst
grader: grader.py
initializationScript: setup.py
backend:
  image: nplaku/ignite-docker
  environment: ignite
